### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by cali72mero** [Rist8/MiSide-Console-Unlocker#6]
at ConsoleUnlocker.Update()
   at Trampoline_VoidThisConsoleUnlockerUpdate(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Void ConsoleCall.CameraFly()'.
   at ConsoleUnlocker.Update()
   at Trampoline_VoidThisConsoleUnlockerUpdate(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Void ConsoleCall.CameraFly()'.
   at ConsoleUnlocker.Update()
   at Trampoline_VoidThisConsoleUnlockerUpdate(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Void ConsoleCall.CameraFly()'.
   at ConsoleUnlocker.Update()
   at Trampoline_VoidThisConsoleUnlockerUpdate(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Void ConsoleCall.CameraFly()'.
   at ConsoleUnlocker.Update()
   at Trampoline_VoidThisConsoleUnlockerUpdate(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Void ConsoleCall.CameraFly()'.
   at ConsoleUnlocker.Update()
   at Trampoline_VoidThisConsoleUnlockerUpdate(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Void ConsoleCall.CameraFly()'.
   at ConsoleUnlocker.Update()
   at Trampoline_VoidThisConsoleUnlockerUpdate(IntPtr , Il2CppMethodInfo* )

**Comment by Rist8** [comment]
fixed in 1.2.1 version
